
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The target system is: Prospero - 10.0 - x86_64
      The host system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files (x86)/SCE/Prospero SDKs/10.000/host_tools/bin/prospero-clang.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.13.9+e0f243f1e for .NET Framework
      Build started 21/03/2025 15:47:48.
      
      Project "C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\3.31.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      _GetBuildSdkVersion:
        Building with PS5 SDK 10.00.00.48
      ClCompile:
        CMakeCXXCompilerId.cpp
        prospero-clang.exe -o Debug\\CMakeCXXCompilerId.o -c -MD -MV -fdiagnostics-format=msvc -Wall -fdiagnostics-parseable-fixits -O0 C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\3.31.0\\CompilerIdCXX\\CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\SCE\\Prospero SDKs\\10.000\\host_tools\\bin\\prospero-lld.exe --vs-diagnostics -o ".\\CompilerIdCXX.elf" --start-group Debug\\CMakeCXXCompilerId.o --end-group
        CompilerIdCXX.vcxproj -> C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\3.31.0\\CompilerIdCXX\\CompilerIdCXX.elf
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\3.31.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:00.56
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.elf"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is Clang, found in:
        C:/Git/MastersTeamProject/AdvancedGameTechnologies/CMakeFiles/3.31.0/CompilerIdCXX/CompilerIdCXX.elf
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Git/MastersTeamProject/AdvancedGameTechnologies/CMakeFiles/CMakeScratch/TryCompile-nciepg"
      binary: "C:/Git/MastersTeamProject/AdvancedGameTechnologies/CMakeFiles/CMakeScratch/TryCompile-nciepg"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: "\t\t\t     "
      CMAKE_CXX_FLAGS_DEBUG: " \t\t -O0 -g -D_DEBUG"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: " \t\t\t\t\t"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Git/MastersTeamProject/AdvancedGameTechnologies/CMakeFiles/CMakeScratch/TryCompile-nciepg'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_ba576.vcxproj /p:Configuration=Debug /p:Platform=Prospero /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.13.9+e0f243f1e for .NET Framework
        Build started 21/03/2025 15:47:50.
        
        Project "C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\CMakeScratch\\TryCompile-nciepg\\cmTC_ba576.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_ba576.dir\\Debug\\".
          Creating directory "C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\CMakeScratch\\TryCompile-nciepg\\Debug\\".
          Creating directory "cmTC_ba576.dir\\Debug\\cmTC_ba576.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_ba576.dir\\Debug\\cmTC_ba576.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_ba576.dir\\Debug\\cmTC_ba576.tlog\\unsuccessfulbuild".
        _GetBuildSdkVersion:
          Building with PS5 SDK 10.00.00.48
        ClCompile:
          CMakeCXXCompilerABI.cpp
          prospero-clang.exe -o cmTC_ba576.dir\\Debug\\CMakeCXXCompilerABI.o -c -MD -MV -fdiagnostics-format=msvc -D_DEBUG -D"CMAKE_INTDIR=\\"Debug\\"" -g -Wall -fdiagnostics-parseable-fixits -O0 -v "C:\\Program Files\\CMake\\share\\cmake-3.31\\Modules\\CMakeCXXCompilerABI.cpp"
          clang version 18.1.6 (PS5 clang version 10.00.0.548 e1fa16f4 selfhost)
          SelfhostVersion: clang version 17.0.6 (ALL clang version 17.00.0.501 cdbd5f6a)
          SIE CONFIDENTIAL
          Copyright (C) 2024 Sony Interactive Entertainment Inc.
          Target: x86_64-sie-ps5
          InstalledDir: C:\\Program Files (x86)\\SCE\\Prospero SDKs\\10.000\\host_tools\\bin
           (in-process)
           "C:\\\\Program Files (x86)\\\\SCE\\\\Prospero SDKs\\\\10.000\\\\host_tools\\\\bin\\\\prospero-clang.exe" -cc1 -triple x86_64-sie-ps5 -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=non-leaf -ffp-contract=on -fdenormal-fp-math=preserve-sign,preserve-sign -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -fno-use-init-array -fvisibility=hidden -fvisibility-global-new-delete=source -fvisibility-from-dllstorageclass -fvisibility-dllexport=protected -fvisibility-nodllstorageclass=keep -fvisibility-externs-dllimport=default -fvisibility-externs-nodllstorageclass=keep -target-cpu znver2s -gno-column-info -fdebug-info-for-profiling -debug-info-kind=limited -dwarf-version=5 -debugger-tuning=sce -gtemplate-alias -mllvm -generate-arange-section -debug-forward-template-params -dwarf-explicit-import "-fdebug-compilation-dir=C:\\\\Git\\\\MastersTeamProject\\\\AdvancedGameTechnologies\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-nciepg" -v -ffunction-sections -fdata-sections "-fcoverage-compilation-dir=C:\\\\Git\\\\MastersTeamProject\\\\AdvancedGameTechnologies\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-nciepg" -resource-dir "C:\\\\Program Files (x86)\\\\SCE\\\\Prospero SDKs\\\\10.000\\\\host_tools\\\\lib\\\\clang" -dependency-file "cmTC_ba576.dir\\\\Debug\\\\CMakeCXXCompilerABI.d" -MT "cmTC_ba576.dir\\\\Debug\\\\CMakeCXXCompilerABI.o" -sys-header-deps -MV -D _DEBUG -D "CMAKE_INTDIR=\\"Debug\\"" -internal-isystem "C:\\\\Program Files (x86)\\\\SCE\\\\Prospero SDKs\\\\10.000\\\\host_tools\\\\lib\\\\clang\\\\include" -internal-externc-isystem "C:\\\\Program Files (x86)\\\\SCE\\\\Prospero SDKs\\\\10.000/target/include" -internal-externc-isystem "C:\\\\Program Files (x86)\\\\SCE\\\\Prospero SDKs\\\\10.000/target/include_common" -O0 -Wall -fdeprecated-macro -ferror-limit 19 -fsuppress-unneeded-method-debug-info -fdiagnostics-parseable-fixits -stack-protector 2 -fno-rtti -fgnuc-version=4.2.1 -sce-stdlib=v1 -fdeclspec -fskip-odr-check-in-gmf -fdiagnostics-format msvc -femit-typedefs-in-template-types -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o "cmTC_ba576.dir\\\\Debug\\\\CMakeCXXCompilerABI.o" -x c++ "C:\\\\Program Files\\\\CMake\\\\share\\\\cmake-3.31\\\\Modules\\\\CMakeCXXCompilerABI.cpp"
          clang -cc1 version 18.1.6 based upon LLVM 18.1.6 default target x86_64-sie-ps5
          #include "..." search starts here:
          #include <...> search starts here:
           C:\\Program Files (x86)\\SCE\\Prospero SDKs\\10.000\\host_tools\\lib\\clang\\include
           C:\\Program Files (x86)\\SCE\\Prospero SDKs\\10.000/target/include
           C:\\Program Files (x86)\\SCE\\Prospero SDKs\\10.000/target/include_common
          End of search list.
        Link:
          C:\\Program Files (x86)\\SCE\\Prospero SDKs\\10.000\\host_tools\\bin\\prospero-lld.exe --vs-diagnostics -o "C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\CMakeScratch\\TryCompile-nciepg\\Debug\\cmTC_ba576.elf" -L"C:/Program Files (x86)/SCE/Prospero SDKs/10.000/target/lib" -L"C:/Program Files (x86)/SCE/Prospero SDKs/10.000/target/lib/Debug" --start-group cmTC_ba576.dir\\Debug\\CMakeCXXCompilerABI.o --end-group -v
          LLD 18.1.6 (PS5 LLD version 10.00.0.548 e1fa16f4 selfhost)
          SelfhostVersion: clang version 17.0.6 (ALL clang version 17.00.0.501 cdbd5f6a)
          SIE CONFIDENTIAL
          Copyright (C) 2024 Sony Interactive Entertainment Inc.
          cmTC_ba576.vcxproj -> C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\CMakeScratch\\TryCompile-nciepg\\Debug\\cmTC_ba576.elf
        FinalizeBuildStatus:
          Deleting file "cmTC_ba576.dir\\Debug\\cmTC_ba576.tlog\\unsuccessfulbuild".
          Touching "cmTC_ba576.dir\\Debug\\cmTC_ba576.tlog\\cmTC_ba576.lastbuildstate".
        Done Building Project "C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\CMakeScratch\\TryCompile-nciepg\\cmTC_ba576.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.46
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:182 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Parsed CXX implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [  C:/Program Files (x86)/SCE/Prospero SDKs/10.000/host_tools/lib/clang/include]
          add: [  C:/Program Files (x86)/SCE/Prospero SDKs/10.000/target/include]
          add: [  C:/Program Files (x86)/SCE/Prospero SDKs/10.000/target/include_common]
        end of search list found
        skipping relative include dir [  C:/Program Files (x86)/SCE/Prospero SDKs/10.000/host_tools/lib/clang/include]
        skipping relative include dir [  C:/Program Files (x86)/SCE/Prospero SDKs/10.000/target/include]
        skipping relative include dir [  C:/Program Files (x86)/SCE/Prospero SDKs/10.000/target/include_common]
        implicit include dirs: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?))("|,| |$)]
        ignore line: [Change Dir: 'C:/Git/MastersTeamProject/AdvancedGameTechnologies/CMakeFiles/CMakeScratch/TryCompile-nciepg']
        ignore line: []
        ignore line: [Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_ba576.vcxproj /p:Configuration=Debug /p:Platform=Prospero /p:VisualStudioVersion=17.0 /v:n]
        ignore line: [MSBuild version 17.13.9+e0f243f1e for .NET Framework]
        ignore line: [Build started 21/03/2025 15:47:50.]
        ignore line: []
        ignore line: [Project "C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\CMakeScratch\\TryCompile-nciepg\\cmTC_ba576.vcxproj" on node 1 (default targets).]
        ignore line: [PrepareForBuild:]
        ignore line: [  Creating directory "cmTC_ba576.dir\\Debug\\".]
        ignore line: [  Creating directory "C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\CMakeScratch\\TryCompile-nciepg\\Debug\\".]
        ignore line: [  Creating directory "cmTC_ba576.dir\\Debug\\cmTC_ba576.tlog\\".]
        ignore line: [InitializeBuildStatus:]
        ignore line: [  Creating "cmTC_ba576.dir\\Debug\\cmTC_ba576.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.]
        ignore line: [  Touching "cmTC_ba576.dir\\Debug\\cmTC_ba576.tlog\\unsuccessfulbuild".]
        ignore line: [_GetBuildSdkVersion:]
        ignore line: [  Building with PS5 SDK 10.00.00.48]
        ignore line: [ClCompile:]
        ignore line: [  CMakeCXXCompilerABI.cpp]
        ignore line: [  prospero-clang.exe -o cmTC_ba576.dir\\Debug\\CMakeCXXCompilerABI.o -c -MD -MV -fdiagnostics-format=msvc -D_DEBUG -D"CMAKE_INTDIR=\\"Debug\\"" -g -Wall -fdiagnostics-parseable-fixits -O0 -v "C:\\Program Files\\CMake\\share\\cmake-3.31\\Modules\\CMakeCXXCompilerABI.cpp"]
        ignore line: [  clang version 18.1.6 (PS5 clang version 10.00.0.548 e1fa16f4 selfhost)]
        ignore line: [  SelfhostVersion: clang version 17.0.6 (ALL clang version 17.00.0.501 cdbd5f6a)]
        ignore line: [  SIE CONFIDENTIAL]
        ignore line: [  Copyright (C) 2024 Sony Interactive Entertainment Inc.]
        ignore line: [  Target: x86_64-sie-ps5]
        ignore line: [  InstalledDir: C:\\Program Files (x86)\\SCE\\Prospero SDKs\\10.000\\host_tools\\bin]
        ignore line: [   (in-process)]
        ignore line: [   "C:\\\\Program Files (x86)\\\\SCE\\\\Prospero SDKs\\\\10.000\\\\host_tools\\\\bin\\\\prospero-clang.exe" -cc1 -triple x86_64-sie-ps5 -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=non-leaf -ffp-contract=on -fdenormal-fp-math=preserve-sign preserve-sign -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -fno-use-init-array -fvisibility=hidden -fvisibility-global-new-delete=source -fvisibility-from-dllstorageclass -fvisibility-dllexport=protected -fvisibility-nodllstorageclass=keep -fvisibility-externs-dllimport=default -fvisibility-externs-nodllstorageclass=keep -target-cpu znver2s -gno-column-info -fdebug-info-for-profiling -debug-info-kind=limited -dwarf-version=5 -debugger-tuning=sce -gtemplate-alias -mllvm -generate-arange-section -debug-forward-template-params -dwarf-explicit-import "-fdebug-compilation-dir=C:\\\\Git\\\\MastersTeamProject\\\\AdvancedGameTechnologies\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-nciepg" -v -ffunction-sections -fdata-sections "-fcoverage-compilation-dir=C:\\\\Git\\\\MastersTeamProject\\\\AdvancedGameTechnologies\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-nciepg" -resource-dir "C:\\\\Program Files (x86)\\\\SCE\\\\Prospero SDKs\\\\10.000\\\\host_tools\\\\lib\\\\clang" -dependency-file "cmTC_ba576.dir\\\\Debug\\\\CMakeCXXCompilerABI.d" -MT "cmTC_ba576.dir\\\\Debug\\\\CMakeCXXCompilerABI.o" -sys-header-deps -MV -D _DEBUG -D "CMAKE_INTDIR=\\"Debug\\"" -internal-isystem "C:\\\\Program Files (x86)\\\\SCE\\\\Prospero SDKs\\\\10.000\\\\host_tools\\\\lib\\\\clang\\\\include" -internal-externc-isystem "C:\\\\Program Files (x86)\\\\SCE\\\\Prospero SDKs\\\\10.000/target/include" -internal-externc-isystem "C:\\\\Program Files (x86)\\\\SCE\\\\Prospero SDKs\\\\10.000/target/include_common" -O0 -Wall -fdeprecated-macro -ferror-limit 19 -fsuppress-unneeded-method-debug-info -fdiagnostics-parseable-fixits -stack-protector 2 -fno-rtti -fgnuc-version=4.2.1 -sce-stdlib=v1 -fdeclspec -fskip-odr-check-in-gmf -fdiagnostics-format msvc -femit-typedefs-in-template-types -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o "cmTC_ba576.dir\\\\Debug\\\\CMakeCXXCompilerABI.o" -x c++ "C:\\\\Program Files\\\\CMake\\\\share\\\\cmake-3.31\\\\Modules\\\\CMakeCXXCompilerABI.cpp"]
        ignore line: [  clang -cc1 version 18.1.6 based upon LLVM 18.1.6 default target x86_64-sie-ps5]
        ignore line: [  #include "..." search starts here:]
        ignore line: [  #include <...> search starts here:]
        ignore line: [   C:\\Program Files (x86)\\SCE\\Prospero SDKs\\10.000\\host_tools\\lib\\clang\\include]
        ignore line: [   C:\\Program Files (x86)\\SCE\\Prospero SDKs\\10.000/target/include]
        ignore line: [   C:\\Program Files (x86)\\SCE\\Prospero SDKs\\10.000/target/include_common]
        ignore line: [  End of search list.]
        ignore line: [Link:]
        ignore line: [  C:\\Program Files (x86)\\SCE\\Prospero SDKs\\10.000\\host_tools\\bin\\prospero-lld.exe --vs-diagnostics -o "C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\CMakeScratch\\TryCompile-nciepg\\Debug\\cmTC_ba576.elf" -L"C:/Program Files (x86)/SCE/Prospero SDKs/10.000/target/lib" -L"C:/Program Files (x86)/SCE/Prospero SDKs/10.000/target/lib/Debug" --start-group cmTC_ba576.dir\\Debug\\CMakeCXXCompilerABI.o --end-group -v]
        ignore line: [  LLD 18.1.6 (PS5 LLD version 10.00.0.548 e1fa16f4 selfhost)]
        ignore line: [  SelfhostVersion: clang version 17.0.6 (ALL clang version 17.00.0.501 cdbd5f6a)]
        ignore line: [  SIE CONFIDENTIAL]
        ignore line: [  Copyright (C) 2024 Sony Interactive Entertainment Inc.]
        ignore line: [  cmTC_ba576.vcxproj -> C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\CMakeScratch\\TryCompile-nciepg\\Debug\\cmTC_ba576.elf]
        ignore line: [FinalizeBuildStatus:]
        ignore line: [  Deleting file "cmTC_ba576.dir\\Debug\\cmTC_ba576.tlog\\unsuccessfulbuild".]
        ignore line: [  Touching "cmTC_ba576.dir\\Debug\\cmTC_ba576.tlog\\cmTC_ba576.lastbuildstate".]
        ignore line: [Done Building Project "C:\\Git\\MastersTeamProject\\AdvancedGameTechnologies\\CMakeFiles\\CMakeScratch\\TryCompile-nciepg\\cmTC_ba576.vcxproj" (default targets).]
        ignore line: []
        ignore line: [Build succeeded.]
        ignore line: [    0 Warning(s)]
        ignore line: [    0 Error(s)]
        ignore line: []
        ignore line: [Time Elapsed 00:00:00.46]
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
